# Generated by Django 3.1.3 on 2021-06-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leapp', '0002_emailsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsender',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
