# Generated by Django 3.1.3 on 2021-06-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leapp', '0003_emailsender_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsender',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
